---
- hosts: ipa
  strategy: free
  become: true
  gather_facts: false
  tasks:
  - name: Setting Up Python
    file:
      src: /usr/bin/python3.6
      path: /usr/bin/python
      state: link
  - name: Setting Hostname
    command: hostnamectl set-hostname ipa.eight.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.150/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search eight.example.com ipv4.method manual
  - name: Reloading Network
    shell: nmcli con up "System eth1"  
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.150 ipa.eight.example.com ipa
      create: yes
  - name: Adding system1 address to hosts file, Installing Packages...
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.151 system1.eight.example.com system1
      create: yes
  - name: Downloading Repo Packages for System1
    shell: dnf group install "GNOME" "Basic Web Server" "Base" -y --downloadonly --destdir=/var/www/html/rpms
  - name: Downloading Additonal Packages
    shell: dnf install -y @idm:DL1 --downloadonly --destdir=/var/www/html/rpms; dnf install vsftpd vdo stratis-cli createrepo pki-ca -y --downloadonly --destdir=/var/www/html/rpms
  - name: Configuring Repo For System
    shell: createrepo /var/www/html/rpms
  - name: Enabling services
    shell: for i in firewalld httpd ; do systemctl enable --now $i;done
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Permissions Fixed. Configuring IPA server...(Est. Time - 7 minutes)
    shell: chmod 644 /usr/lib/python3.6/site-packages/urllib3/packages/ssl_match_hostname.py;chmod u+x /usr/lib/python3.6/site-packages/urllib3/packages/ssl_match_hostname.py 
  - name: Setting SELinux To Permissive
    shell: setenforce 0
#    async: 1500
#    poll: 0
#    register: ipa_config_sleeper
#    ignore_errors: yes
#  - name: Still Working On IPA Configuration...It takes time ¯\_(ツ)_/¯
#    async_status: jid={{ ipa_config_sleeper.ansible_job_id }}
#    register: job_result
#    until: job_result.finished
#    retries: 200
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #             _         _         _          
         #           /\ \      /\ \      / /\        
         #           \ \ \    /  \ \    / /  \       
         #           /\ \_\  / /\ \ \  / / /\ \      
         #          / /\/_/ / / /\ \_\/ / /\ \ \     
         #         / / /   / / /_/ / / / /  \ \ \    
         #        / / /   / / /__\/ / / /___/ /\ \   
         #       / / /   / / /_____/ / /_____/ /\ \  
         #   ___/ / /__ / / /     / /_________/\ \ \ 
         #  /\__\/_/___/ / /     / / /_       __\ \_\
         #  \/_________\/_/      \_\___\     /____/_/
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into `hostname`
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # You are logged in as `whoami`
         #
         "
...