---
- name: Setting up Repo Server
  hosts: repo
  strategy: free
  ignore_errors: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    hostname: name=repo.eight.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.149/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n192.168.55.149 repo.eight.example.com repo\n192.168.55.150 server1.eight.example.com server1\n192.168.55.151 server2.eight.example.com server2"
      force: yes
  - name: Starting services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - firewalld
      - httpd
  - name: Enabling Firewall Services
    firewalld: 
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http 
      - https 
      - ntp 
      - dns
      - ftp
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Fixing SELinux Contexts
    shell: restorecon -Rv /var/www/html
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         "
