---
- hosts: repo
  strategy: free
  become: true
  gather_facts: false
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname repo.eight.example.com
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.149/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.150 ipa.eight.example.com ipa
      create: yes
  - name: Adding system1 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.151 system1.eight.example.com system1
      create: yes
  - name: Adding Repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.149 repo.eight.example.com repo
      create: yes
  - name: Enabling services
    shell: for i in httpd firewalld ; do systemctl enable $i;done
  - name: Starting services
    shell: for i in httpd firewalld ; do systemctl start $i;done
    ignore_errors: true
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Fixing SELinux Contexts
    shell: restorecon -Rv /var/www/html
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as user \"`whoami`\"
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         "
...